# GNU Make project makefile autogenerated by Premake
ifndef config
  config=server
endif

ifndef verbose
  SILENT = @
endif

ifndef CC
  CC = gcc
endif

ifndef CXX
  CXX = g++
endif

ifndef AR
  AR = ar
endif

ifeq ($(config),server)
  OBJDIR     = obj/Server/io
  TARGETDIR  = bin
  TARGET     = $(TARGETDIR)/libgmsv_io_win32.dylib
  DEFINES   += -DNDEBUG -DSERVER -DGMMODULE
  INCLUDES  += -I../../include -I../../source/LuaOO/include
  CPPFLAGS  += -MMD -MP $(DEFINES) $(INCLUDES)
  CFLAGS    += $(CPPFLAGS) $(ARCH) -g -msse -O2 -ffast-math -fPIC
  CXXFLAGS  += $(CFLAGS) 
  LDFLAGS   += -dynamiclib -flat_namespace -Lbin
  LIBS      += -lLuaOO
  RESFLAGS  += $(DEFINES) $(INCLUDES) 
  LDDEPS    += bin/libLuaOO.a
  LINKCMD    = $(CXX) -o $(TARGET) $(OBJECTS) $(LDFLAGS) $(RESOURCES) $(ARCH) $(LIBS)
  define PREBUILDCMDS
  endef
  define PRELINKCMDS
  endef
  define POSTBUILDCMDS
  endef
endif

ifeq ($(config),client)
  OBJDIR     = obj/Client/io
  TARGETDIR  = bin
  TARGET     = $(TARGETDIR)/libio.dylib
  DEFINES   += -DNDEBUG -DCLIENT -DGMMODULE
  INCLUDES  += -I../../include -I../../source/LuaOO/include
  CPPFLAGS  += -MMD -MP $(DEFINES) $(INCLUDES)
  CFLAGS    += $(CPPFLAGS) $(ARCH) -g -msse -O2 -ffast-math -fPIC
  CXXFLAGS  += $(CFLAGS) 
  LDFLAGS   += -dynamiclib -flat_namespace -Lbin
  LIBS      += -lLuaOO
  RESFLAGS  += $(DEFINES) $(INCLUDES) 
  LDDEPS    += bin/libLuaOO.a
  LINKCMD    = $(CXX) -o $(TARGET) $(OBJECTS) $(LDFLAGS) $(RESOURCES) $(ARCH) $(LIBS)
  define PREBUILDCMDS
  endef
  define PRELINKCMDS
  endef
  define POSTBUILDCMDS
  endef
endif

ifeq ($(config),serveruniv32)
  OBJDIR     = obj/Universal32/Server/io
  TARGETDIR  = bin
  TARGET     = $(TARGETDIR)/libgmsv_io_win32.dylib
  DEFINES   += -DNDEBUG -DSERVER -DGMMODULE
  INCLUDES  += -I../../include -I../../source/LuaOO/include
  CPPFLAGS  +=  $(DEFINES) $(INCLUDES)
  CFLAGS    += $(CPPFLAGS) $(ARCH) -g -msse -O2 -ffast-math -arch i386 -arch ppc -fPIC
  CXXFLAGS  += $(CFLAGS) 
  LDFLAGS   += -dynamiclib -flat_namespace -arch i386 -arch ppc -Lbin
  LIBS      += -lLuaOO
  RESFLAGS  += $(DEFINES) $(INCLUDES) 
  LDDEPS    += bin/libLuaOO.a
  LINKCMD    = $(CXX) -o $(TARGET) $(OBJECTS) $(LDFLAGS) $(RESOURCES) $(ARCH) $(LIBS)
  define PREBUILDCMDS
  endef
  define PRELINKCMDS
  endef
  define POSTBUILDCMDS
  endef
endif

ifeq ($(config),clientuniv32)
  OBJDIR     = obj/Universal32/Client/io
  TARGETDIR  = bin
  TARGET     = $(TARGETDIR)/libio.dylib
  DEFINES   += -DNDEBUG -DCLIENT -DGMMODULE
  INCLUDES  += -I../../include -I../../source/LuaOO/include
  CPPFLAGS  +=  $(DEFINES) $(INCLUDES)
  CFLAGS    += $(CPPFLAGS) $(ARCH) -g -msse -O2 -ffast-math -arch i386 -arch ppc -fPIC
  CXXFLAGS  += $(CFLAGS) 
  LDFLAGS   += -dynamiclib -flat_namespace -arch i386 -arch ppc -Lbin
  LIBS      += -lLuaOO
  RESFLAGS  += $(DEFINES) $(INCLUDES) 
  LDDEPS    += bin/libLuaOO.a
  LINKCMD    = $(CXX) -o $(TARGET) $(OBJECTS) $(LDFLAGS) $(RESOURCES) $(ARCH) $(LIBS)
  define PREBUILDCMDS
  endef
  define PRELINKCMDS
  endef
  define POSTBUILDCMDS
  endef
endif

OBJECTS := \
	$(OBJDIR)/io.o \
	$(OBJDIR)/file.o \
	$(OBJDIR)/lua.o \
	$(OBJDIR)/fileObject.o \
	$(OBJDIR)/pathObject.o \
	$(OBJDIR)/path.o \

RESOURCES := \

SHELLTYPE := msdos
ifeq (,$(ComSpec)$(COMSPEC))
  SHELLTYPE := posix
endif
ifeq (/bin,$(findstring /bin,$(SHELL)))
  SHELLTYPE := posix
endif

.PHONY: clean prebuild prelink

all: $(TARGETDIR) $(OBJDIR) prebuild prelink $(TARGET)
	@:

$(TARGET): $(GCH) $(OBJECTS) $(LDDEPS) $(RESOURCES)
	@echo Linking io
	$(SILENT) $(LINKCMD)
	$(POSTBUILDCMDS)

$(TARGETDIR):
	@echo Creating $(TARGETDIR)
ifeq (posix,$(SHELLTYPE))
	$(SILENT) mkdir -p $(TARGETDIR)
else
	$(SILENT) mkdir $(subst /,\\,$(TARGETDIR))
endif

$(OBJDIR):
	@echo Creating $(OBJDIR)
ifeq (posix,$(SHELLTYPE))
	$(SILENT) mkdir -p $(OBJDIR)
else
	$(SILENT) mkdir $(subst /,\\,$(OBJDIR))
endif

clean:
	@echo Cleaning io
ifeq (posix,$(SHELLTYPE))
	$(SILENT) rm -f  $(TARGET)
	$(SILENT) rm -rf $(OBJDIR)
else
	$(SILENT) if exist $(subst /,\\,$(TARGET)) del $(subst /,\\,$(TARGET))
	$(SILENT) if exist $(subst /,\\,$(OBJDIR)) rmdir /s /q $(subst /,\\,$(OBJDIR))
endif

prebuild:
	$(PREBUILDCMDS)

prelink:
	$(PRELINKCMDS)

ifneq (,$(PCH))
$(GCH): $(PCH)
	@echo $(notdir $<)
	-$(SILENT) cp $< $(OBJDIR)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -c "$<"
endif

$(OBJDIR)/io.o: ../../source/io/io.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -c "$<"
$(OBJDIR)/file.o: ../../source/io/file/file.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -c "$<"
$(OBJDIR)/lua.o: ../../source/io/lua/lua.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -c "$<"
$(OBJDIR)/fileObject.o: ../../source/io/lua/object/fileObject.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -c "$<"
$(OBJDIR)/pathObject.o: ../../source/io/lua/object/pathObject.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -c "$<"
$(OBJDIR)/path.o: ../../source/io/path/path.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -c "$<"

-include $(OBJECTS:%.o=%.d)
